version: '3'

services:

  webserver:
    container_name: blog_nginx
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php
    networks:
      - blog

  php:
    container_name: blog_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    networks:
      - blog
    links:
      - mysql
      - redis

  mysql:
    container_name: blog_mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3333:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - blog

  redis:
    container_name: blog_redis
    image: 'redis:alpine'
    volumes:
      - ./docker/redis:/data
    networks:
      - blog
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]

networks:
  blog:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local